### PR TITLE
Expose the declaration file

### PR DESCRIPTION
**Pull request by mindsers**
Copy the declaration file from `src` to `dist` before publishing

The file will be available from the public package (`graphql-tag.macro/index.d.ts`)

### CODE REVIEW

**Comment by zackify** [comment]
I think if you use —copy-files with Babel it will make manually copying unnecessary.

**Comment by mindsers** [comment]
@zackify Great point! But babel copies everything not compiled. So the files that are in the `--ignore` flag are copied too.

Capture d’écran 2019-08-21 à 22 41 59

Should we `cp` or `--copy-files` then `rm` files?

**Comment by zackify** [comment]
Good point! It looks good to me. I will approve. But will wait and see if @audiolion or @leoasis can review quickly before merging

**Review by zackify — APPROVED** [review]

**Comment by mindsers** [comment]
Just read the TypeScript documentation and saw: 

> ## Including declarations in your npm package
> If your package has a main .js file, you will need to indicate the main declaration file in your package.json file as well. Set the types property to point to your bundled declaration file. 

So, I updated this PR to follow the documentation. 😖

**Comment by zackify** [comment]
Nice, I didn’t know that. In my one public package I wrote types for, I just did the declaration export next to each file. Good to know.

**Comment by zackify** [comment]
I released graphql-tag.macro@2.0.1, try it out. thanks again

**Comment by mindsers** [comment]
@zackify Is there a mistake on the version number?

**Pull request merged**
