### PR TITLE
Fix babel-macros has been renamed to babel-plugin-macros

### LINKED ISSUE #2: babel-macros is now babel-plugin-macros.
See https://www.npmjs.com/package/babel-macros

### PR DESCRIPTION
**Pull request by mufasa71**
Fix #2

### CODE REVIEW

**Comment by frederikhors** [comment]
@leoasis please merge...

**Comment by frederikhors** [comment]
@leoasis and release... :)

**Comment by frederikhors** [comment]
@mufasa71 what do you think?

**Comment by mufasa71** [comment]
@frederikhors As I know jest require for babel-core. I can remove `^`, but since `yarn.lock` is there

**Comment by frederikhors** [comment]
@mufasa71 I tried on my WIndows with both yarn and npm: `babel-core` is a problem for both. I removed it and everything works good.

**Comment by mufasa71** [comment]
@frederikhors I tried to remove and its not working on linux. Also I found official documentations related to this https://jestjs.io/docs/en/getting-started#using-babel Any suggestions?

**Comment by sebastienfi** [comment]
I went ahead and found Leonardo on Facebook, asked him to add a few maintainers to merge this PR asap. Stay tuned!

**Comment by frederikhors** [comment]
> @frederikhors I tried to remove and its not working on linux. Also I found official documentations related to this https://jestjs.io/docs/en/getting-started#using-babel Any suggestions?

Can you retry? It works on my PC.

**Comment by zackify** [comment]
Any way for us to install this ourselves? I was going to point to the branch but I figure there is a build step

**Comment by frederikhors** [comment]
@zackify you have to build it yourself and use github.com/some in `package.json` until any of use can be mantainer and to all the work.

We are waiting for @leoasis.

I also opened this: https://github.com/apollographql/apollo-feature-requests/issues/58

**Comment by zackify** [comment]
@frederikhors this is listed as MIT maybe we should fork and publish ourselves?

**Comment by frederikhors** [comment]
@zackify I think we should wait a little more time.

**Comment by sebastienfi** [comment]
No news from Leonardo yet.
I ended up adding a prebuild script which simply replace the name of the import in `node_modules/graphql-tag.macro/dist/index.js` prior to we pack compilation.
Let's wait a couple more days, then forking under a new package seems best.

**Comment by zackify** [comment]
I was chatting with him on Twitter today, he said tomorrow he might add me as a contributor :)

**Comment by leoasis** [comment]
Sorry for not being active, I was actually on vacation this last week. I'll get this sorted out with the help of @zackify today 💃

**Comment by leoasis** [comment]
Thanks for the PR @mufasa71! It seems to be working fine, I'll make a release for this. Sorry again for taking so long to get to this

**Pull request merged**
